const TermsPage = () => {
  return (
    <main className="flex-1 animate-fade-in-up">
      {/* Hero */}
      <section className="text-center py-16 sm:py-20 px-4 sm:px-6 max-w-4xl mx-auto">
        <h1 className="text-3xl sm:text-5xl font-serif font-bold text-text-primary mb-4">Terms of Service</h1>
        <p className="text-text-secondary">Last updated: February 18, 2026</p>
      </section>

      {/* Content */}
      <section className="px-4 sm:px-6 pb-16 sm:pb-24 max-w-[800px] mx-auto">
        <div className="space-y-8">
          <div>
            <h2 className="text-xl font-bold text-text-primary mb-3">1. Acceptance of Terms</h2>
            <p className="text-text-secondary leading-relaxed">
              By accessing or using Smart Learn Today's platform, website, and services (the "Service"), you agree to be bound by these Terms of Service. If you do not agree, you may not use the Service.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-bold text-text-primary mb-3">2. Description of Service</h2>
            <p className="text-text-secondary leading-relaxed">
              Smart Learn Today provides AI-powered study tools, including but not limited to: an AI tutor, quiz generator, flashcard creator, study note summarizer, and progress tracking. The Service is designed to assist with learning and is not a substitute for professional academic instruction.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-bold text-text-primary mb-3">3. User Accounts</h2>
            <ul className="list-disc list-outside ml-6 space-y-2 text-text-secondary">
              <li>You must provide accurate and complete information when creating an account.</li>
              <li>You are responsible for maintaining the confidentiality of your login credentials.</li>
              <li>You must be at least 13 years old to use the Service.</li>
              <li>One user per account; sharing accounts is not permitted.</li>
            </ul>
          </div>

          <div>
            <h2 className="text-xl font-bold text-text-primary mb-3">4. Acceptable Use</h2>
            <p className="text-text-secondary leading-relaxed mb-3">You agree not to:</p>
            <ul className="list-disc list-outside ml-6 space-y-2 text-text-secondary">
              <li>Use the Service for academic dishonesty, plagiarism, or fraud</li>
              <li>Upload harmful, illegal, or offensive content</li>
              <li>Attempt to reverse-engineer, hack, or exploit the platform</li>
              <li>Resell or redistribute AI-generated content commercially</li>
              <li>Use automated tools to scrape or collect data from the Service</li>
            </ul>
          </div>

          <div>
            <h2 className="text-xl font-bold text-text-primary mb-3">5. Intellectual Property</h2>
            <p className="text-text-secondary leading-relaxed">
              All content, features, and functionality of the Service are owned by Smart Learn Today and protected by copyright, trademark, and other intellectual property laws. You retain ownership of the content you upload (e.g., study notes), but grant us a license to process it for providing the Service.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-bold text-text-primary mb-3">6. AI-Generated Content</h2>
            <p className="text-text-secondary leading-relaxed">
              Responses generated by our AI tutor are for educational purposes only. While we strive for accuracy, AI-generated content may contain errors. You should verify important information with authoritative sources. We are not liable for decisions made based on AI-generated content.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-bold text-text-primary mb-3">7. Subscription & Billing</h2>
            <ul className="list-disc list-outside ml-6 space-y-2 text-text-secondary">
              <li>Free tier users have limited access as described on our Pricing page.</li>
              <li>Paid subscriptions are billed monthly or annually and auto-renew unless cancelled.</li>
              <li>Refunds are available within 14 days of purchase for annual plans.</li>
              <li>We reserve the right to change pricing with 30 days' notice.</li>
            </ul>
          </div>

          <div>
            <h2 className="text-xl font-bold text-text-primary mb-3">8. Termination</h2>
            <p className="text-text-secondary leading-relaxed">
              We may suspend or terminate your account if you violate these Terms. You may delete your account at any time through your account settings. Upon termination, your right to use the Service ceases immediately.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-bold text-text-primary mb-3">9. Limitation of Liability</h2>
            <p className="text-text-secondary leading-relaxed">
              Smart Learn Today is provided "as is" without warranties of any kind. To the fullest extent permitted by law, we shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-bold text-text-primary mb-3">10. Contact</h2>
            <p className="text-text-secondary leading-relaxed">
              For questions about these Terms, please contact us at{" "}
              <a href="mailto:legal@smartlearntoday.com" className="text-indigo-600 hover:underline font-medium">legal@smartlearntoday.com</a>.
            </p>
          </div>
        </div>
      </section>
    </main>
  );
};

export default TermsPage;
